from app import *
import requests
import json
from flask import jsonify
from project import db

# File used for database & API setup only
url = "http://localhost:5000/products/"
food_headers = {"X-API-KEY": "food"}
textile_headers = {"X-API-KEY": "textile"}
food_products = json.load(open('sample_food_products.json', 'r'))
textile_products = json.load(open('sample_textile_products.json', 'r'))
with app.app_context():
    db.drop_all()
    db.create_all()
sample_textile = dict(textile_products[0])
sample_textile.pop("id") # Will be generated by DB when added
sample_food = dict(food_products[1])
sample_food.pop("id")
print(sample_food)

response = requests.post(url, data=json.dumps(sample_food), headers={"X-API-KEY": "food", "ContentType": "application/json"})




get_food = requests.get(url, headers=food_headers)
#get_textile = requests.get(url, headers=textile_headers)
print()
print(get_food.json())

#print(get_textile.json())
#print(get_textile.status_code)
