from app import *
import requests
import json
from test_app import url, food_headers, textile_headers, food_products, textile_products
from flask import jsonify

# File used for database & API setup only

db.drop_all()
db.create_all()
sample_textile = dict(textile_products[0])
sample_textile.pop("id") # Will be generated by DB when added
sample_food = dict(food_products[1])
sample_food.pop("id")
print(sample_food)

response = requests.post(url, data=json.dumps(sample_food), headers={"X-API-KEY": "food", "ContentType": "application/json"})




get_food = requests.get(url, headers=food_headers)
#get_textile = requests.get(url, headers=textile_headers)
print()
print(get_food.json())

#print(get_textile.json())
#print(get_textile.status_code)
