from app import *
import requests
import json
from test_app import url, food_headers, textile_headers, food_products, textile_products

# File used for database & API setup only

get_food = requests.get(url, headers=food_headers)
get_textile = requests.get(url, headers=textile_headers)
print(get_food.json())
print(get_food.status_code)
print()
print(get_textile.json())
print(get_textile.status_code)

sample_textile = dict(textile_products[0])
sample_textile.pop("id") # Will be generated by DB when added
sample_food = dict(food_products[0])
sample_food.pop("id")
print(sample_textile)
