import requests
import json
import unittest
from http import HTTPStatus
from flask_testing import TestCase
from project import db, create_app
from project.config import Testing

food_products = json.load(open('sample_food_products.json', 'r'))
textile_products = json.load(open('sample_textile_products.json', 'r'))
url = "http://localhost:5000/products/"
food_headers = {"X-API-KEY": "food"}
textile_headers = {"X-API-KEY": "textile"}

class TestAPI(TestCase):

    def create_app(self):
        return create_app(config=Testing)

    def setUp(self):
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

    def test_get_food(self): # GET should return all food products in DB
        self.maxDiff = None
        response = requests.get(url, headers=food_headers).json()
        self.assertEqual(response, food_products)

    def test_post_food(self): # Check for successful food product add
        data = food_products[0]
        data.pop("id", None) # Remove id key (auto generated by DB)
        response = requests.post(url, data=data, headers=food_headers)
        self.assertEqual(response.status_code, HTTPStatus.CREATED)

    def test_post_none_food(self): # POST with no JSON data should give BAD_REQUEST
        data = {}
        response = requests.post(url, data=data, headers=food_headers)
        self.assertEqual(response.status_code, HTTPStatus.BAD_REQUEST)

    def test_get_textile(self): # GET should return all textile products in DB
        response = requests.get(url, headers=textile_headers).json()
        self.assertEqual(response, textile_products)

    def test_post_textile(self): # Check for successful textile product add
        data = textile_products[0]
        data.pop("id", None) # Remove id key (auto generated by DB)
        response = requests.post(url, data=data, headers=textile_headers)
        self.assertEqual(response.status_code, HTTPStatus.CREATED)

    def test_post_none_textile(self): # POST with no JSON data should give BAD_REQUEST
        data = {}
        response = requests.post(url, data=data, headers=textile_headers)
        self.assertEqual(response.status_code, HTTPStatus.BAD_REQUEST)


if __name__ == "__main__":
    unittest.main()
