import json
import unittest
import pytest
from http import HTTPStatus
from project import db, create_app
from config import Testing
from flask import request
from project.models import *

food_products = json.load(open('sample_food_products.json', 'r'))
textile_products = json.load(open('sample_textile_products.json', 'r'))
url = "http://127.0.0.1:5000/products/"
food_headers = {"X-API-KEY": "food"}
textile_headers = {"X-API-KEY": "textile"}

@pytest.fixture(scope="module")
def app():
    app = create_app(config=Testing)
    return app

@pytest.fixture(scope="module")
def client(app):
    client = app.test_client()
    return client

@pytest.yield_fixture(scope='function', autouse=True)
def setup_db(app):
    with app.app_context(): # Called before each test
        db.create_all()
    yield
    with app.app_context(): # Called after each test
        db.drop_all()
        db.session.remove()

def test_get_none(client):
    response = client.get(url, headers=food_headers)
    assert response.status_code == HTTPStatus.OK
    assert response.get_json() == []
    response = client.get(url, headers=textile_headers)
    assert response.status_code == HTTPStatus.OK
    assert response.get_json() == []

def test_get_food(client): # Adds a product manually and checks response
    db.session.add(Product(name='Chorizo', product_type='food'))
    db.session.add(Food(product_id=1, family='sausage', customer='Deans Butchers'))
    db.session.add(Allergen(name='cereals'))
    db.session.add(ProductAllergen(allergen_id=1, product_id=1))
    db.session.add(Material(material_name='paprika', quantity=100, units='tablespoons', product_id=1))
    db.session.add(Material(material_name='pork mince', quantity=10, units='kg', product_id=1))
    db.session.add(Tag(tag_name='spicy'))
    db.session.add(ProductTag(tag_id=1, product_id=1))
    db.session.add(ProductTag(tag_id=2, product_id=1))
    db.session.add(Tag(tag_name='spanish'))
    db.session.commit()
    response = client.get(url, headers=food_headers)
    data = food_products[0]
    data.pop("id", None) # Auto generated by DB
    product = response.get_json()[0]
    product.pop("id", None)
    assert product == data
    assert response.status_code == HTTPStatus.OK

def test_get_textile(client):
    db.session.add(Product(name='Tweed Jacket', product_type='textile'))
    db.session.add(Textile(product_id=1, colour='Maroon', range='Grandad Chic'))
    db.session.add(Material(material_name='Maroon wool', quantity=100, units='metres', product_id=1))
    db.session.add(Material(material_name='Silk lining', quantity=10, units='square metres', product_id=1))
    db.session.add(Tag(tag_name='mens'))
    db.session.add(ProductTag(tag_id=1, product_id=1))
    db.session.add(ProductTag(tag_id=2, product_id=1))
    db.session.add(Tag(tag_name='smart'))
    db.session.add(ProductTag(tag_id=3, product_id=1))
    db.session.add(Tag(tag_name='suits'))
    db.session.commit()
    response = client.get(url, headers=textile_headers)
    data = textile_products[0]
    data.pop("id", None)
    product = response.get_json()[0]
    product.pop("id", None)
    assert product == data
    assert response.status_code == HTTPStatus.OK

def test_post_none_food(client):
    data = {}
    response = client.post(url, data=json.dumps(data), headers=food_headers)
    assert response.status_code == HTTPStatus.BAD_REQUEST

def test_post_none_textile(client):
    data = {}
    response = client.post(url, data=json.dumps(data), headers=textile_headers)
    assert response.status_code == HTTPStatus.BAD_REQUEST

def test_post_food(client):
    data = food_products[0]
    data.pop("id", None)
    response = client.post(url, data=json.dumps(data), headers=food_headers) # Adds new product
    assert response.status_code == HTTPStatus.CREATED
    response = client.get(url, headers=food_headers) # Retrieves new proudct & checks it is correct
    product = response.get_json()[0]
    product.pop("id", None)
    assert response.status_code == HTTPStatus.OK
    assert product == data

def test_post_textile(client):
    data = textile_products[0]
    data.pop("id", None)
    response = client.post(url, data=json.dumps(data), headers=textile_headers)
    assert response.status_code == HTTPStatus.CREATED
    response = client.get(url, headers=textile_headers) # Retrieves new proudct & checks it is correct
    product = response.get_json()[0]
    product.pop("id", None)
    assert response.status_code == HTTPStatus.OK
    assert product == data

def test_post_incorrect_api_key(client):
    headers = {'X-API-KEY': 'qwerty'}
    data = food_products[0]
    data.pop("id", None) # Remove id key (auto generated by DB)
    response = client.post(url, data=json.dumps(data), headers=headers)
    assert response.status_code == HTTPStatus.BAD_REQUEST
